### PR TITLE
Verbose show connection info

### PR DESCRIPTION
**Pull request by indera**

### CODE REVIEW

**Comment by NavidMitchell** [comment]
Thank you for the interest in helping with Structures. 

I am curious as to why you wanted to add logging to.

function receiveSessionId(scope: string): Promise<string> 

Did you have a problem that you were trying to chase down and the logging was not sufficient to find the problem?

**Comment by indera** [comment]
I am not familiar with the all the moving parts involved in `Continuum.connect`
it appears that this is the relevant code https://github.com/Kinotic-Foundation/continuum-framework/blob/eb060f0adfd92f79a01ac301cc8fb88b2f989dab/continuum-js/continuum-client/src/core/api/EventBus.ts#L114

What I am observing during testing is that (after 30 seconds) this error shows and I am not sure what is wrong

```
Could not connect to the Structures Server. Please check the server is running and the URL is correct. TimeoutError: Connection timeout trying to connect to the Structures Server
```

== Debugging done

```
CONTAINER ID              NAMES                           STATUS                        PORTS
aa829e320a9c              opsramp-structures-server-1     Up 23 minutes (unhealthy)     127.0.0.1:4000->4000/tcp, 127.0.0.1:8080->8080/tcp, 127.0.0.1:9090->9090/tcp, 127.0.0.1:58503-58504->58503-58504/tcp
fd3e7e73ddd9              elasticsearch                   Up 10 hours (healthy)         0.0.0.0:9200->9200/tcp, 9300/tcp
c31ff0af650a              keycloak                        Up 10 hours                   8080/tcp, 127.0.0.1:8888->8888/tcp
```

Restarting `opsramp-structures-server-1 ` container shows it as 
```
health: starting
```

Health check
```
curl --silent --fail 127.0.0.1:9090/health
{"checks":[{"id":"elasticsearch","status":"UP"}],"outcome":"UP"}
```

And after 2 minutes it changes to 
```
Up 2 minutes (unhealthy)
```

**Comment by NavidMitchell** [comment]
It looks like due to the state of the structures-server the CLI could not connect. So it is timing out here.

```typescript
    const connectedInfo: ConnectedInfo = await pTimeout(Continuum.connect(connectionInfo), {
            milliseconds: 30000,
            message: 'Connection timeout trying to connect to the Structures Server'
        })
```        

I will talk with Nick about your setup and see whats going on.

**Comment by indera** [comment]
Closing since it appears that my docker was acting strangely. 

I can  re-open the PR if needed :)

**Pull request closed without merging**
